version: '3.7'

services:
  windowing:
    image: core-windowing:latest
    environment:
      DATA_USER_ID: 5ed93a900857444fa43b8417
      DATA_JOB_ID: 5f46d94d3233a07f34471d0f
      DATA_TOKEN: 3e52de96-57d1-4ac1-9849-1e0d617df7c3
    volumes:
      - <your_path>/<user_id>/jobs/<job_id>:/job
    network_mode: bridge
