name: docker

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Rename .env.example
        run: mv .env.example .env

      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v2

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
